# Site settings
title: Physics applets
email: davidfokkema@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Applets demonstrating several physics phenomena, without all the fuss.
  There is a lot of freedom in the interactions, and the design is
  minimalistic.
baseurl: "/physics-applets" # the subpath of your site, e.g. /blog/
url: "http://davidfokkema.github.io" # the base hostname & protocol for your site
twitter_username: davidfokkema
github_username:  davidfokkema

# Build settings
markdown: kramdown
